student_count = 11
# First, we print the list of students
puts "The students of Villain Academy"
puts "------------"
puts "Dr Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Micheal Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
puts "Overall, we have #{student_count} great students"